[env:ch32x035]
platform = ch32v
board = genericCH32X035F7P6

build_flags =
    -nostartfiles
    -Wl,-T"src/link.ld"
    -Os
    -ffunction-sections
    -fdata-sections
    -Wl,--gc-sections
    -Wl,--no-relax
    -mno-relax

upload_protocol = ch32-1k2touch
extra_scripts = pre:ch32_1k2touch.py

build_src_filter =
    +<*>
